# Generated by Django 4.2.4 on 2023-08-17 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exaggerated', models.BooleanField()),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='record.checkin')),
                ('symptoms', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='record.symptoms')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exaggerated', models.BooleanField()),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='record.behavior')),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='record.checkin')),
            ],
        ),
    ]
