# Generated by Django 4.2.4 on 2023-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_rename_checkinsymptoms_checkinsymptom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='name',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='datetime',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
